# ---
#
# Examples Makefile
#
# Compiles all examples
#
# Copyright (c) 2014-2018 Mattias Mattsson. All rights reserved.
# This source is distributed under the license in LICENSE.txt in the top
# InstaWorks directory.
#
# ---

.PHONY: all clean

all: 
	$(MAKE) -C simple -f Makefile
	$(MAKE) -C philosophers -f Makefile

clean:
	$(MAKE) -C simple -f Makefile clean
	$(MAKE) -C philosophers -f Makefile clean

# ---

