# ---
#
# Examples Makefile
#
# Compiles all examples
#
# Copyright (C) Mattias Mattsson - 2014
#
# ---

.PHONY: all clean

all: 
	$(MAKE) -C simple -f Makefile
	$(MAKE) -C philosophers -f Makefile

clean:
	$(MAKE) -C simple -f Makefile clean
	$(MAKE) -C philosophers -f Makefile clean

# ---

